# Generated by Django 4.1 on 2022-12-10 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        db_column="id", primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(db_column="name", max_length=45)),
                ("tel", models.CharField(db_column="tel", max_length=45)),
                ("address", models.CharField(db_column="address", max_length=45)),
                ("website", models.CharField(db_column="website", max_length=45)),
                (
                    "image",
                    models.ImageField(db_column="image", upload_to="school_img/"),
                ),
                (
                    "public_private",
                    models.CharField(db_column="public/private", max_length=45),
                ),
                ("union", models.CharField(db_column="union", max_length=45)),
                (
                    "school_system",
                    models.CharField(db_column="school_system", max_length=45),
                ),
            ],
            options={"db_table": "school",},
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        db_column="id", primary_key=True, serialize=False
                    ),
                ),
                ("member_id", models.CharField(db_column="member_id", max_length=45)),
                ("name", models.CharField(db_column="name", max_length=45)),
                ("identity", models.CharField(db_column="identity", max_length=45)),
                ("sex", models.CharField(db_column="sex", max_length=45)),
                ("birthday", models.DateField(db_column="birthday")),
                ("tel", models.CharField(db_column="tel", max_length=45)),
                ("email", models.EmailField(db_column="email", max_length=45)),
                ("password", models.CharField(db_column="password", max_length=45)),
                (
                    "image",
                    models.ImageField(db_column="image", upload_to="member_img/"),
                ),
                (
                    "school_id",
                    models.ForeignKey(
                        db_column="school_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Member.school",
                    ),
                ),
            ],
            options={"db_table": "member",},
        ),
    ]
