# Generated by Django 3.2.16 on 2022-12-18 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'managed': False},
        ),
    ]
